### ISSUE TITLE
Not compatible with English version

### ISSUE THREAD

**Issue by Zhao-Yuting** [wtsnjp/nlproceedings#2]
I use nlp2021_latex_template for writing the English version. But the figure/table caption and reference section title are compiled in characters (like 表１/　図１/ 参考文献). Could you please help to solve this problem? (I hope the latext_templete can be compiled as Table 1/ Figure 1 / Reference.) Thank you in advance!

**Comment by wtsnjp** [comment]
Same as the standard LaTeX classes, you can change those names by redefining `\tablename` etc. in your preamble, e.g.,

```tex
\renewcommand{\contentsname}{Table of Contents}
\renewcommand{\refname}{References}
\renewcommand{\indexname}{Index}
\renewcommand{\listfigurename}{List of Figures}
\renewcommand{\figurename}{Figure}
\renewcommand{\listtablename}{List of Tables}
\renewcommand{\tablename}{Table}
```
