### ISSUE TITLE
Some problems about English version.

### ISSUE THREAD

**Issue by Zhao-Yuting** [wtsnjp/nlproceedings#3]
Hi, there,
I use this source file to compile an English version. I found that the captions of Figure/Table are compiled with Figure1/Table1, which have no space between Figure/Table and 1. I hope that Figure 1/ Table 1 can be compiled. Moreover, in the reference, there is also no space between the reference number and paper information (like: ''[1]Ilya Sutskever,** Oriol Vinyals,''). I hope the reference could be compiled as ''[1]  Ilya Sutskever, Oriol Vinyals.''
Would you please tell me how to solve this problem? I really appreciate any help you can provide.

**Comment by wtsnjp** [comment]
For figure and table names, I have added a new option `english` in branch [nlp2021-en](https://github.com/wtsnjp/nlproceedings/tree/nlp2021-en). Please have a try:

```tex
\documentclass[lualatex,english]{nlp2021}
```

With this option, you can remove the redefinitions of `\refname` etc. that I mentioned in #2.

> Moreover, in the reference, there is also no space between the reference number and paper information (like: ''[1]Ilya Sutskever,** Oriol Vinyals,'').

This does not reproduce for me. Maybe you didn't give an appropriate number to the `thebibliography` environment? Could you provide a minimal working example?

**Comment by Zhao-Yuting** [comment]
> This does not reproduce for me. Maybe you didn't give an appropriate number to the `thebibliography` environment? Could you provide a minimal working example?

Reply: After using your new branch for En version, this problem has been solved!

Additionally, the problem about Figure/Table has also been solved by using the new en branch. 
Thank you very much! Have a nice day~

**Comment by Zhao-Yuting** [comment]
Excuse me, after using the new en version, I found new problems.
The interlinkage for the reference and Figure/Table are disappeared.
For example, in the text "BLEU (B) [28] andMETEOR(M) [29] metrics," the number [28] and [29] have no link function. When I click the [28]/[29], there is no action. (In the former version, the [28]/[29] is blue font and has link function. But now the font of these number is black, and no link function any more.)
The same problem with Figure and Table, in the text "As shown in Table 1," nothing happens when I click the number "1,"  do you have any ideas? 
Thank you in advance!

**Comment by wtsnjp** [comment]
Did you load the `hyperref` package?

**Comment by Zhao-Yuting** [comment]
👍 It has been solved now! Thank you for your cooperation!
