### ISSUE TITLE
LuaLaTeX 環境で正しくタイプライタ体が設定されない

### ISSUE THREAD

**Issue by naughie** [wtsnjp/nlproceedings#4]
言語処理学会第30回年次大会（NLP2024）用のクラスファイルを[原稿提出要項](https://www.anlp.jp/nlp2024/submit.html)からダウンロードしました．

以下のサンプルを `lualatex sample.tex` でタイプセットした場合，正しいフォントが使用されず，Computer (Latin?) Modern Roman らしきフォントが使われてしまいます．

```
\documentclass[lualatex]{nlp2024}

\begin{document}

\texttt{"l'}

\end{document}
```

エンジンを (u)pLaTeX にした場合は，（おそらく意図した通り）Inconsolata フォントが使用されます．

これはクラスファイル `nlp2024.cls` 内でフォントの設定を

```
\RequirePackage[varqu,varl]{inconsolata}
```

としているのが原因で，Stack Exchange にも[同様の報告](https://tex.stackexchange.com/questions/408566/usepackageinconsolata-changes-ttfamily-to-serif-non-monospace-font)がある他，[CTAN](https://ctan.org/pkg/inconsolata?lang=en) の Package documentation の末尾にも，Opentype issues で説明されています．

`inconsolata` の Package documentation では次のような解決策が提案されていますが，これは二つの理由で上手く動きません．

```
\documentclass{article}
\usepackage{fontspec}
\setmonofont[StylisticSet={1,3}]{Inconsolatazi4}

\begin{document}

\texttt{"l'}

\end{document}
```

1. (u)pLaTeX の `varqu,varl` オプションと同じ挙動，つまり
    a. シングルクォートは curly
    b. ダブルクォートは upright
    c. `l` (lower L) は shapely
  を実現することができない．
2. 文書クラスを `nlp2024.cls` にすると `Package fontspec Error: The font "Inconsolatazi4" cannot be found.` というエラーが出る．

前者は Inconsolata の OTF ファイルの問題で，後者はおそらく `jlreq` クラスの問題でしょうか．

詳しく調査していないので確かな原因も解決策も不明ですが，issue として報告いたします．

**Comment by naughie** [comment]
申し訳ありません．書き忘れていましたが，確認した環境は以下の通りです．

- OS: Ubuntu 22.04 LTS
- TeX version:
```
$ tex --version
TeX 3.141592653 (TeX Live 2023)
kpathsea version 6.3.5
Copyright 2023 D.E. Knuth.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the TeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the TeX source.
Primary author of TeX: D.E. Knuth.
```
- upLaTeX version:
```
$ uplatex --version
e-upTeX 3.141592653-p4.1.0-u1.29-230214-2.6 (utf8.uptex) (TeX Live 2023)
kpathsea version 6.3.5
ptexenc version 1.4.3
Copyright 2023 D.E. Knuth.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the e-upTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the e-upTeX source.
Primary author of e-upTeX: Japanese TeX Development Community.
```
- LuaLaTeX version:
```
$ lualatex --version
This is LuaHBTeX, Version 1.17.0 (TeX Live 2023)
Development id: 7581

Execute  'luahbtex --credits'  for credits and version details.

There is NO warranty. Redistribution of this software is covered by
the terms of the GNU General Public License, version 2 or (at your option)
any later version. For more information about these matters, see the file
named COPYING and the LuaTeX source.

LuaTeX is Copyright 2022 Taco Hoekwater and the LuaTeX Team.

```

**Comment by wtsnjp** [comment]
ご報告ありがとうございます。

2についてはLuaTeX-jaで使用する場合は`Inconsolatazi4-Regular`とウェイトまで含めて指定する必要があるようですが、このように指定すれば動きそうです。

1の問題はフォント側（OTF）の問題であればすぐの解決は難しそうですが、そこまで深刻ではないと思うので一旦現状のワークアラウンドでもよいかなという気もします。
